# Generated by Django 2.2.12 on 2020-05-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'dato de usuario', 'verbose_name_plural': 'Datos de usuarios '},
        ),
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Rol usuario', 'verbose_name_plural': 'Roles de los usuarios'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades del usuario', 'verbose_name_plural': 'Habilidades de los usuarios'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de habilidad', 'verbose_name_plural': 'Niveles de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='datosuser',
            name='direccion',
            field=models.CharField(max_length=255, null=True, verbose_name='direccion de usuario'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='generoUser',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=10, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modificado'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='nombreUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='profecionUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Profecion'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='upData',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado'),
        ),
        migrations.AddField(
            model_name='detaroles',
            name='addUser',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de agregacion de user'),
        ),
        migrations.AddField(
            model_name='habilidades',
            name='descipcionHabilidad',
            field=models.TextField(default='Desarrollador', max_length=2000, null=True, verbose_name='Descripcion de habilidad'),
        ),
        migrations.AddField(
            model_name='rates',
            name='udtHabilidad',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de actualizacion de la habilidad'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='fotoUser',
            field=models.ImageField(default='user.png', null=True, upload_to='imgPerfil/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='telUser',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono del usuario'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='userDNI',
            field=models.CharField(max_length=20, verbose_name='ID de el usuario'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='Agregado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de agregacion del rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='EstadoRol',
            field=models.CharField(default='activo', max_length=20, verbose_name='Estado del rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idRoles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Id del rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del usuario'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='nombreHabilidad',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de la habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Porcentaje de dominio de la habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='idHabilidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Habilidades', verbose_name='Id de la habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='idUSuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del usuario'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roleName',
            field=models.CharField(default='usuario', max_length=50, verbose_name='Nombre del rol'),
        ),
    ]
